=== sergmain/dbrevision/trunk/src/main/xsd/dbrevision.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2007 Sergei Maslyukov at riverock.org
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dbrevision-structure="http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd">
	<xs:annotation>
		<xs:documentation>Copyright 2002-2007, Riverock, http://www.riverock.org</xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>DbRevision framework, http://dbrevision.sourceforge.net</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd" schemaLocation="dbrevision-structure.xsd"/>
	<xs:element name="DbRevision">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Module" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Versions">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Version" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Patches">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Patch" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Patch">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="PreviousName" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Name of definition, which must be processed before this definition</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Validator" minOccurs="0"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="Action"/>
					<xs:element ref="CustomClassAction"/>
					<xs:element ref="SqlAction"/>
					<xs:element ref="AddTableFieldAction"/>
					<xs:element ref="TableData"/>
					<xs:element name="Table" type="dbrevision-structure:DbTable"/>
					<xs:element name="Sequence" type="dbrevision-structure:DbSequence"/>
					<xs:element name="ForeignKey" type="dbrevision-structure:DbForeignKey"/>
					<xs:element name="Index" type="dbrevision-structure:DbIndex"/>
					<xs:element name="PrimaryKey" type="dbrevision-structure:DbPrimaryKey"/>
					<xs:element name="View" type="dbrevision-structure:DbView"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="isProcessed" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TableData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RecordData" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="tableName" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RecordData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FieldData" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FieldData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TypeField">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="string"/>
							<xs:enumeration value="date"/>
							<xs:enumeration value="number"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:choice>
					<xs:element name="StringData" type="xs:string" minOccurs="0"/>
					<xs:element name="DateData" type="xs:dateTime" minOccurs="0"/>
					<xs:element name="NumberData" type="xs:decimal" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="fieldName" type="xs:string" use="required"/>
			<xs:attribute name="isNull" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Action">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="CUSTOM_SQL"/>
							<xs:enumeration value="CUSTOM_CLASS_ACTION"/>
							<xs:enumeration value="CREATE_SEQUENCE"/>
							<xs:enumeration value="CREATE_TABLE"/>
							<xs:enumeration value="ADD_TABLE_COLUMN"/>
							<xs:enumeration value="DROP_TABLE_COLUMN"/>
							<xs:enumeration value="ADD_PRIMARY_KEY"/>
							<xs:enumeration value="ADD_FOREIGN_KEY"/>
							<xs:enumeration value="DROP_PRIMARY_KEY"/>
							<xs:enumeration value="DROP_FOREIGN_KEY"/>
							<xs:enumeration value="DROP_TABLE"/>
							<xs:enumeration value="DROP_SEQUENCE"/>
							<xs:enumeration value="DELETE_BEFORE_FK"/>
							<xs:enumeration value="COPY_COLUMN"/>
							<xs:enumeration value="CLONE_COLUMN"/>
							<xs:enumeration value="COPY_TABLE"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="ActionParameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Validator">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Class" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ActionParameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Data" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SqlAction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Sql" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CustomClassAction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Class" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AddTableFieldAction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Field" type="dbrevision-structure:DbField"/>
			</xs:sequence>
			<xs:attribute name="tableName" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sergmain/dbrevision/trunk/src/test/configs/config-4/webmill/5.7.1/patch/patch-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Patches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\..\..\main\xsd\dbrevision.xsd">
	<Patch>
		<Name>patch-2</Name>
        <PreviousName>patch-1</PreviousName>
        <Action>
            <Type>CUSTOM_CLASS_ACTION</Type>
            <ActionParameter name="class_name">
                <Data>org.riverock.db.definition.InitWebmillStructureV2</Data>
            </ActionParameter>
        </Action>
	</Patch>
</Patches>

=== sergmain/dbrevision/src/test/resources/xml/patch/patch-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Patches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\main\xsd\dbrevision.xsd">
	<Patch>
		<Name>test_2_1</Name>
		<PreviousName>test_1_1</PreviousName>
		<PrimaryKey schemaName="MILLENNIUM" tableName="TEST_1_1" pkName="ID_TEST11_T11_PK">
			<Column columnName="ID_TEST11" keySeq="1" />
		</PrimaryKey>
        <ForeignKey pkSchemaName="MILLENNIUM" pkTableName="TEST_1_1" pkName="ID_TEST11_T11_PK" fkSchemaName="MILLENNIUM" fkTableName="TEST_1_2" fkName="ID_TEST11_T12_FK">
            <Column pkColumnName="ID_TEST11" fkColumnName="ID_TEST11" keySeq="1"/>  
            <DeleteRule ruleType="0" ruleName="java.sql.DatabaseMetaData.importedKeyCascade"/>
            <Deferrability ruleType="7" ruleName="java.sql.DatabaseMetaData.importedKeyNotDeferrable"/>
        </ForeignKey>
	</Patch>
	<Patch>
		<Name>test_1_0</Name>
		<PreviousName>test_0_0</PreviousName>
        <Sequence name="SEQ_TEST_1_1" minValue="1" maxValue="99999" incrementBy="1" lastNumber="1"/>
        <Sequence name="SEQ_TEST_1_2" minValue="1" maxValue="99999" incrementBy="1" lastNumber="1"/>
	</Patch>
	<Patch>
		<Name>test_1_2</Name>
		<PreviousName>test_1_1</PreviousName>
        <Table schema="MILLENNIUM" name="TEST_1_2" type="TABLE" remark="Test table 1-2">
            <Field name="ID_TEST12" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="4" decimalDigit="0" nullable="0"/>
            <Field name="ID_TEST11" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="4" decimalDigit="0" nullable="0"/>
            <Field name="NAME_TEST12" dataType="VARCHAR2" javaType="12" javaStringType="java.sql.Types.VARCHAR" size="30" decimalDigit="0" nullable="0"/>
        </Table>
	</Patch>
	<Patch>
		<Name>test_1_1</Name>
		<PreviousName>test_1_0</PreviousName>
        <Table schema="MILLENNIUM" name="TEST_1_1" type="TABLE" remark="Test table 1-1">
            <Field name="ID_TEST11" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="4" decimalDigit="0" nullable="0"/>
            <Field name="NAME_TEST11" dataType="VARCHAR2" javaType="12" javaStringType="java.sql.Types.VARCHAR" size="30" decimalDigit="0" nullable="0"/>
        </Table>
	</Patch>
	<Patch>
		<Name>test_0_0</Name>
			<Action>
                <Type>CUSTOM_SQL</Type>
                <ActionParameter name="sql">
                    <Data>DROP TABLE TEST_1_2</Data>
				</ActionParameter>
			</Action>
			<Action>
				<Type>DROP_TABLE</Type>
				<ActionParameter name="name_table">
						<Data>TEST_1_2</Data>
				</ActionParameter>
			</Action>
	</Patch>
	<Patch>
		<Name>test_0_2</Name>
		<PreviousName>test_0_1</PreviousName>
		<View schema="MILLENNIUM" name="F_DEL_V_B2C_ITEMS_PRICE_SIMPLE" type="VIEW">
			<Text>select  a1.*, e.name_currency, e.id_currency
from
(select a.*, b.id_site from price_list a, price_shop_table b
where a.id_shop = b.id_shop and   a.absolete = 0
) a1, cash_currency e
where   a1.currency = e.currency(+) and
        a1.id_site = e.id_site(+)
            </Text>
		</View>
		<View schema="MILLENNIUM" name="F_D_V_AUTH_ARM_FULL" type="VIEW">
			<Text>select distinct b.id_arm, code_arm from auth_arm b WITH READ ONLY</Text>
		</View>
		<View schema="MILLENNIUM" name="V_RELATE_RIGHT_FULL" type="VIEW">
			<Text>select a.id_relate_right, a.id_access_group, a.id_object_arm, a.code_right,

c.name_object_arm, c.code_object_arm, c.name_arm, c.id_arm,
b.name_access_group, c.code_arm, is_road, is_service, is_firm
from v_relate_right_arm a, auth_access_group b, V_AUTH_MODULE_FULL c
where a.id_object_arm = c.id_object_arm and a.id_access_group = b.id_access_group
            </Text>
		</View>
		<Sequence name="FOR_DEL_SEQ_A" minValue="0" maxValue="9999" incrementBy="1" isCycle="false" isOrder="false" cacheSize="0" lastNumber="2"/>
		<Sequence name="LIST_GROUP_PRODUCT_SEQ" minValue="1" maxValue="99999999999999999999999999" incrementBy="1" isCycle="false" isOrder="false" cacheSize="0" lastNumber="11"/>
		<Table schema="MILLENNIUM" name="A_TEST" type="TABLE">
			<PrimaryKey schemaName="MILLENNIUM" tableName="A_TEST" pkName="ID_TEST_LANG_A_TEST_PK">
                <Column columnName="ID_TEST" keySeq="1"/>
				<Column columnName="ID_LANG" keySeq="2"/>
			</PrimaryKey>
			<Field name="ID_TEST" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="22" decimalDigit="0" nullable="0"/>
			<Field name="ID_LANG" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="22" decimalDigit="0" nullable="0"/>
			<Field name="TYPE" dataType="VARCHAR2" javaType="12" javaStringType="java.sql.Types.VARCHAR" size="30" decimalDigit="0" nullable="1"/>
			<Field name="IS_YESNO" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="1" decimalDigit="0" nullable="0" defaultValue="1"/>
		</Table>
		<Table schema="MILLENNIUM" name="A_TEST_" type="TABLE">
			<Field name="ID_TEST_1" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="22" decimalDigit="0" nullable="1"/>
			<Field name="ID_TEST" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="22" decimalDigit="0" nullable="1"/>
			<Field name="ID_LANG" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="22" decimalDigit="0" nullable="1"/>
			<Field name="NAMER" dataType="VARCHAR2" javaType="12" javaStringType="java.sql.Types.VARCHAR" size="20" decimalDigit="0" nullable="1"/>
		</Table>
	</Patch>
</Patches>
