=== sergmain/dbrevision/src/main/xsd/dbrevision-structure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ org.riverock.dbrevision - Database revision framework
  ~ For more information about DbRevision, please visit project site
  ~ http://dbrevision.sourceforge.net
  ~
  ~ Copyright (C) 2006-2007, Riverock Software, All Rights Reserved.
  ~
  ~ Riverock - The Open-source Java Development Community
  ~ http://www.riverock.org
  ~
  ~
  ~ This library is free software; you can redistribute it and/or
  ~ modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either
  ~ version 2.1 of the License, or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this library; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dbrevision-structure="http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd" targetNamespace="http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd">
	<xs:annotation>
		<xs:documentation>Copyright 2002-2007 riverock.org, http://www.riverock.org</xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>DbRevision framework, http://dbrevision.sourceforge.net</xs:documentation>
	</xs:annotation>
	<xs:complexType name="DbDatabase">
		<xs:sequence>
			<xs:element name="Schema" type="dbrevision-structure:DbSchema"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="SchemaElement" type="dbrevision-structure:DbSchema"/>
	<xs:complexType name="DbSchema">
		<xs:sequence>
			<xs:element name="Table" type="dbrevision-structure:DbTable" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="View" type="dbrevision-structure:DbView" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="ViewReplacement" type="dbrevision-structure:DbViewReplacement" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Sequence" type="dbrevision-structure:DbSequence" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
    <xs:complexType name="DbViewReplacement">
        <xs:sequence>
            <xs:element name="DatabaseFamily" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation source="Типы баз данных десь должны совпдать с типми в классе org.riverock.dbrevision.db.DatabaseFactory">
                        org.riverock.dbrevision.db.DatabaseFactory

                        public static final String ORACLE_FAMILY = "oracle";
                        public static final String MYSQL_FAMILY = "mysql";
                        public static final String HYPERSONIC_FAMILY = "hypersonic";
                        public static final String SQLSERVER_FAMILY = "sqlserver";
                        public static final String POSTGREES_FAMILY = "postgrees";
                        public static final String DB2_FAMILY = "db2";
                        public static final String MAXDB_FAMILY = "maxdb";
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="oracle"/>
                        <xs:enumeration value="mysql"/>
                        <xs:enumeration value="hypersonic"/>
                        <xs:enumeration value="sqlserver"/>
                        <xs:enumeration value="postgrees"/>
                        <xs:enumeration value="db2"/>
                        <xs:enumeration value="maxdb"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="View" type="dbrevision-structure:DbView" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Skip" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
	<xs:complexType name="DbAbstractTable" abstract="true">
		<xs:attribute name="schema" type="xs:string"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="remark" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DbView">
		<xs:complexContent>
			<xs:extension base="dbrevision-structure:DbAbstractTable">
				<xs:sequence>
					<xs:element name="Text" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DbTable">
		<xs:complexContent>
			<xs:extension base="dbrevision-structure:DbAbstractTable">
				<xs:sequence>
					<xs:element name="PrimaryKey" type="dbrevision-structure:DbPrimaryKey" minOccurs="0"/>
					<xs:element name="Field" type="dbrevision-structure:DbField" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="ForeignKey" type="dbrevision-structure:DbForeignKey" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="Index" type="dbrevision-structure:DbIndex" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="Data" type="dbrevision-structure:DbDataTable" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DbSequence">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="minValue" type="xs:int" use="required"/>
		<xs:attribute name="maxValue" type="xs:string" use="required"/>
		<xs:attribute name="incrementBy" type="xs:int" use="required"/>
		<xs:attribute name="isCycle" type="xs:boolean"/>
		<xs:attribute name="isOrder" type="xs:boolean"/>
		<xs:attribute name="cacheSize" type="xs:int"/>
		<xs:attribute name="lastNumber" type="xs:long" use="required"/>
	</xs:complexType>
	<xs:complexType name="DbField">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="dataType" type="xs:string">
			<xs:annotation>
				<xs:documentation source="Тип поля как он есть в базе"/>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="applType" type="xs:string"/>
		<xs:attribute name="javaType" type="xs:int"/>
		<xs:attribute name="javaStringType" type="xs:string"/>
		<xs:attribute name="size" type="xs:int" use="optional"/>
		<xs:attribute name="decimalDigit" type="xs:int"/>
		<xs:attribute name="nullable" type="xs:int"/>
		<xs:attribute name="defaultValue" type="xs:string"/>
		<xs:attribute name="comment" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DbPrimaryKey">
		<xs:sequence>
			<xs:element name="Column" type="dbrevision-structure:DbPrimaryKeyColumn" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="catalogName" type="xs:string"/>
		<xs:attribute name="schemaName" type="xs:string"/>
		<xs:attribute name="tableName" type="xs:string" use="required"/>
		<xs:attribute name="pkName" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DbPrimaryKeyColumn">
		<xs:attribute name="columnName" type="xs:string" use="required"/>
		<xs:attribute name="keySeq" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="DbForeignKey">
		<xs:sequence>
			<xs:element name="Column" type="dbrevision-structure:DbForeignKeyColumn" maxOccurs="unbounded"/>
			<xs:element name="UpdateRule" type="dbrevision-structure:DbKeyActionRule" minOccurs="0"/>
			<xs:element name="DeleteRule" type="dbrevision-structure:DbKeyActionRule" minOccurs="0"/>
			<xs:element name="Deferrability" type="dbrevision-structure:DbKeyActionRule" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="pkSchemaName" type="xs:string"/>
		<xs:attribute name="pkTableName" type="xs:string"/>
		<xs:attribute name="pkName" type="xs:string" use="required"/>
		<xs:attribute name="fkSchemaName" type="xs:string"/>
		<xs:attribute name="fkTableName" type="xs:string" use="required"/>
		<xs:attribute name="fkName" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DbForeignKeyColumn">
		<xs:attribute name="pkColumnName" type="xs:string"/>
		<xs:attribute name="fkColumnName" type="xs:string"/>
		<xs:attribute name="keySeq" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="DbIndex">
		<xs:sequence>
			<xs:element name="Column" type="dbrevision-structure:DbIndexColumn" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="catalogName" type="xs:string"/>
		<xs:attribute name="schemaName" type="xs:string"/>
		<xs:attribute name="tableName" type="xs:string" use="required"/>
		<xs:attribute name="indexName" type="xs:string"/>
		<xs:attribute name="isNonUnique" type="xs:boolean"/>
		<xs:attribute name="indexQualifier" type="xs:string"/>
		<xs:attribute name="type" type="xs:int"/>
		<xs:attribute name="cardinality" type="xs:int"/>
		<xs:attribute name="pages" type="xs:int"/>
		<xs:attribute name="filterCondition" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DbIndexColumn">
		<xs:attribute name="columnName" type="xs:string" use="required"/>
		<xs:attribute name="keySeq" type="xs:int" use="required"/>
		<xs:attribute name="ascending" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="DbKeyActionRule">
		<xs:attribute name="ruleType" type="xs:int"/>
		<xs:attribute name="ruleName" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DbDataSchema">
		<xs:sequence>
			<xs:element name="Tables" type="dbrevision-structure:DbDataTable" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DbDataTable">
		<xs:sequence>
			<xs:element name="Record" type="dbrevision-structure:DbDataRecord" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DbDataRecord">
		<xs:sequence>
			<xs:element name="FieldData" type="dbrevision-structure:DbDataFieldData" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DbDataFieldData">
		<xs:sequence>
			<xs:element name="JavaTypeField" type="xs:int"/>
			<xs:element name="StringData" type="xs:string" minOccurs="0"/>
			<xs:element name="DateData" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="NumberData" type="xs:decimal" minOccurs="0"/>
			<xs:element name="IsNull" type="xs:boolean"/>
		</xs:sequence>
		<xs:attribute name="size" type="xs:int" use="optional"/>
		<xs:attribute name="decimalDigit" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== sergmain/dbrevision/src/test/resources/xml/init-structure/init-structure.xml
<?xml version="1.0" encoding="utf-8"?>
<dbrevision-structure:SchemaElement xmlns:dbrevision-structure="http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd
dbrevision-structure.xsd">

	<Table schema="TEST" name="WM_PORTAL_IDS" type="TABLE">
		<Field name="sequence_name" dataType="VARCHAR2" javaType="12" javaStringType="java.sql.Types.VARCHAR" size="50" nullable="1"/>
		<Field name="sequence_next_value" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="10" decimalDigit="0" nullable="1"/>
	</Table>
	<Table schema="TEST" name="WM_AUTH_ACCESS_GROUP" type="TABLE">
		<PrimaryKey>
			<Column schemaName="TEST" tableName="WM_AUTH_ACCESS_GROUP" columnName="ID_ACCESS_GROUP" keySeq="1" pkName="ID_AG_AAG_PK"/>
		</PrimaryKey>
		<Field name="ID_ACCESS_GROUP" dataType="NUMBER" javaType="3" javaStringType="java.sql.Types.DECIMAL" size="10" decimalDigit="0" nullable="0"/>
		<Field name="NAME_ACCESS_GROUP" dataType="VARCHAR2" javaType="12" javaStringType="java.sql.Types.VARCHAR" size="100" nullable="1"/>
	</Table>

	<Sequence name="SEQ_WM_PRICE_QUERY_TABLE" minValue="1" maxValue="999999999999999999999999" incrementBy="1" isCycle="false" isOrder="false" cacheSize="0" lastNumber="29"/>
</dbrevision-structure:SchemaElement>
